### ISSUE TITLE
Support for Lombok

### ISSUE THREAD

**Issue by umangm99** [aemide/issues#708]
Hi AEM IDE Team,

We use Lombok for generating getters in our code but seems like AEM IDE is not supporting Lombok annotations yet. Can you please look into this. Thanks

**Comment by karollewandowski** [comment]
Hi Umang,
Thank you for requesting it.
Do you mean Sling Models used in HTL? Could you please provide some examples?

**Comment by umangm99** [comment]
Hi @karollewandowski  thanks for replying so quickly. Yes in my AEM Sling models I'm using @Getter annotation provided by Lombok library and using Lombok extension with my IntelliJ Idea.

AEM IDE plugin complains in my HTL files that getter is not available when I try to use any injected object in HTL.

**Comment by umangm99** [comment]
https://projectlombok.org/features/ is link to project Lombok and you can integrate in AEM AEM project by adding in pom.xml. Instructions at https://www.baeldung.com/intro-to-project-lombok

If you are using IntelliJ Idea then you can use https://plugins.jetbrains.com/plugin/6317-lombok to make Idea understand that you are using Lombok annotations.

My ask is if AEM IDE also starts to understand that I'm using Lombok annotations and not through errors then it will make my day while keeping my code more clean.

**Comment by karollewandowski** [comment]
Hi @umangm99.

Sorry for the delay.

It turns out that AEM IDE works with Lombok out of the box.
Please make sure that you enabled annotation processors in the IDE:
https://www.baeldung.com/lombok-ide#intellij-apt

I verified it in the latest version of AEM IDE:
<img width="1594" alt="Screenshot 2024-03-14 at 22 33 15" src="https://github.com/aemide/issues/assets/1154140/9141fc3b-f7c6-4269-9483-3b9e70c150ba">

I'm closing the issue. Please reopen in case of additional questions.
